import {
  Accessibility,
  Bell,
  BookOpen,
  Bot,
  CheckCircle2,
  ChevronRight,
  Cloud,
  CircleGauge,
  ClipboardList,
  Contrast,
  FileText,
  FolderOpen,
  GraduationCap,
  Home,
  LayoutDashboard,
  LogOut,
  Mail,
  Menu,
  Moon,
  PauseCircle,
  Pencil,
  PlayCircle,
  Plus,
  RefreshCcw,
  Search,
  Send,
  Settings,
  Sparkles,
  Trash2,
  Upload,
  Users,
  X,
  type LucideIcon,
} from "lucide-react";

const icons = {
  accessibility: Accessibility,
  bell: Bell,
  book: BookOpen,
  bot: Bot,
  check: CheckCircle2,
  chevron: ChevronRight,
  cloud: Cloud,
  contrast: Contrast,
  dashboard: LayoutDashboard,
  file: FileText,
  folder: FolderOpen,
  gauge: CircleGauge,
  graduation: GraduationCap,
  home: Home,
  list: ClipboardList,
  logout: LogOut,
  mail: Mail,
  menu: Menu,
  moon: Moon,
  pause: PauseCircle,
  pencil: Pencil,
  play: PlayCircle,
  plus: Plus,
  refresh: RefreshCcw,
  search: Search,
  send: Send,
  settings: Settings,
  sparkles: Sparkles,
  trash: Trash2,
  upload: Upload,
  users: Users,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function Icon({ name, className = "h-5 w-5", label }: { name: IconName; className?: string; label?: string }) {
  const Component = icons[name];
  return <Component aria-label={label} aria-hidden={label ? undefined : true} className={className} strokeWidth={2.2} />;
}
